name: news-outlets
channels:
  - conda-forge
dependencies:
  - python=3.11
  - networkx
  - python-igraph
  - seaborn
  - pandas
  - python-igraph
  - graph-tool
  - scikit-learn
  - numpy
  - scipy
  - pip
  - pip:
      - -r requirements.txt
  






