news-outlets:
  target: dev_fal
  outputs:
    dev_fal:
      type: fal
      db_profile: dev_bq
    dev_bq:
      project: gannett-enterprise-data-dev
      dataset: dbt_cecil
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      threads: 4
      type: bigquery